### ISSUE TITLE
Could not open input file: /var/www/html/artisan

### ISSUE THREAD

**Issue by mdabagh** [HassanHelfi/local-laravel-docker#1]
Hi Mr Helfi
I have problem to use command "docker-compose exec php php /var/www/html/artisan config:clear" .
I get this error after this command when I put laravel in 'src/laravel' path: "Could not open input file: /var/www/html/artisan" .

I get this error after this command when I put laravel in 'src' path:
Fatal error: Uncaught Error: Class "Illuminate\Foundation\Application" not found in /var/www/html/bootstrap/app.php:14
Stack trace:
#0 /var/www/html/artisan(20): require_once()
#1 {main}
  thrown in /var/www/html/bootstrap/app.php on line 14

---
windows 11 , install docker on ubuntu windows 10 and wsl2

**Comment by HassanHelfi** [comment]
Hi 
be sure to add you laravel source into src Dir for example
```
 ├─ local-laravel-docker
 └──┬── src
    ├──── app
    ├──── bootstrap
    ├──── config
    └──── ...
```
this error is because it does not find the artisan
